// Copyright 2019-2022 @polkadot/extension-koni authors & contributors
// SPDX-License-Identifier: Apache-2.0

export const CRON_REFRESH_PRICE_INTERVAL = 30000;
export const DOTSAMA_API_TIMEOUT = 30000;
export const DOTSAMA_AUTO_CONNECT_MS = 3000;
export const DOTSAMA_MAX_CONTINUE_RETRY = 9;
export const CRON_AUTO_RECOVER_DOTSAMA_INTERVAL = 60000;
export const ACALA_REFRESH_CROWDLOAN_INTERVAL = 30000;
export const ACALA_REFRESH_BALANCE_INTERVAL = 30000;
export const MOONBEAM_REFRESH_BALANCE_INTERVAL = 30000;
export const CRON_REFRESH_NFT_INTERVAL = 30000;
export const CRON_REFRESH_STAKING_REWARD_INTERVAL = 90000;
export const CRON_REFRESH_HISTORY_INTERVAL = 2000;

export const ALL_ACCOUNT_KEY = 'ALL';
export const IGNORE_GET_SUBSTRATE_FEATURES_LIST: string[] = ['astarEvm'];
