// Copyright 2017-2022 @subwallet/extension-koni-base authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@subwallet/extension-koni-base', path: 'auto', type: 'auto', version: '0.4.9-0' };
