"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.MOONBEAM_REFRESH_BALANCE_INTERVAL = exports.IGNORE_GET_SUBSTRATE_FEATURES_LIST = exports.DOTSAMA_MAX_CONTINUE_RETRY = exports.DOTSAMA_AUTO_CONNECT_MS = exports.DOTSAMA_API_TIMEOUT = exports.CRON_REFRESH_STAKING_REWARD_INTERVAL = exports.CRON_REFRESH_PRICE_INTERVAL = exports.CRON_REFRESH_NFT_INTERVAL = exports.CRON_REFRESH_HISTORY_INTERVAL = exports.CRON_AUTO_RECOVER_WEB3_INTERVAL = exports.CRON_AUTO_RECOVER_DOTSAMA_INTERVAL = exports.ASTAR_REFRESH_BALANCE_INTERVAL = exports.ALL_ACCOUNT_KEY = exports.ACALA_REFRESH_CROWDLOAN_INTERVAL = exports.ACALA_REFRESH_BALANCE_INTERVAL = void 0;
// Copyright 2019-2022 @polkadot/extension-koni authors & contributors
// SPDX-License-Identifier: Apache-2.0
const CRON_REFRESH_PRICE_INTERVAL = 30000;
exports.CRON_REFRESH_PRICE_INTERVAL = CRON_REFRESH_PRICE_INTERVAL;
const DOTSAMA_API_TIMEOUT = 30000;
exports.DOTSAMA_API_TIMEOUT = DOTSAMA_API_TIMEOUT;
const DOTSAMA_AUTO_CONNECT_MS = 3000;
exports.DOTSAMA_AUTO_CONNECT_MS = DOTSAMA_AUTO_CONNECT_MS;
const DOTSAMA_MAX_CONTINUE_RETRY = 9;
exports.DOTSAMA_MAX_CONTINUE_RETRY = DOTSAMA_MAX_CONTINUE_RETRY;
const CRON_AUTO_RECOVER_DOTSAMA_INTERVAL = 60000;
exports.CRON_AUTO_RECOVER_DOTSAMA_INTERVAL = CRON_AUTO_RECOVER_DOTSAMA_INTERVAL;
const CRON_AUTO_RECOVER_WEB3_INTERVAL = 90000;
exports.CRON_AUTO_RECOVER_WEB3_INTERVAL = CRON_AUTO_RECOVER_WEB3_INTERVAL;
const ACALA_REFRESH_CROWDLOAN_INTERVAL = 30000;
exports.ACALA_REFRESH_CROWDLOAN_INTERVAL = ACALA_REFRESH_CROWDLOAN_INTERVAL;
const ACALA_REFRESH_BALANCE_INTERVAL = 30000;
exports.ACALA_REFRESH_BALANCE_INTERVAL = ACALA_REFRESH_BALANCE_INTERVAL;
const ASTAR_REFRESH_BALANCE_INTERVAL = 30000;
exports.ASTAR_REFRESH_BALANCE_INTERVAL = ASTAR_REFRESH_BALANCE_INTERVAL;
const MOONBEAM_REFRESH_BALANCE_INTERVAL = 30000;
exports.MOONBEAM_REFRESH_BALANCE_INTERVAL = MOONBEAM_REFRESH_BALANCE_INTERVAL;
const CRON_REFRESH_NFT_INTERVAL = 900000;
exports.CRON_REFRESH_NFT_INTERVAL = CRON_REFRESH_NFT_INTERVAL;
const CRON_REFRESH_STAKING_REWARD_INTERVAL = 900000;
exports.CRON_REFRESH_STAKING_REWARD_INTERVAL = CRON_REFRESH_STAKING_REWARD_INTERVAL;
const CRON_REFRESH_HISTORY_INTERVAL = 2000;
exports.CRON_REFRESH_HISTORY_INTERVAL = CRON_REFRESH_HISTORY_INTERVAL;
const ALL_ACCOUNT_KEY = 'ALL';
exports.ALL_ACCOUNT_KEY = ALL_ACCOUNT_KEY;
const IGNORE_GET_SUBSTRATE_FEATURES_LIST = ['astarEvm'];
exports.IGNORE_GET_SUBSTRATE_FEATURES_LIST = IGNORE_GET_SUBSTRATE_FEATURES_LIST;