// Copyright 2017-2021 @polkadot/extension-inject authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/extension-inject', version: '0.38.3-0' };
