// Copyright 2017-2022 @polkadot/extension-inject authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/extension-inject', path: 'auto', type: 'auto', version: '0.2.5-3' };
