export default const networkUris = {
    Polkadot:	polkadot.api.subscan.io,
    Kusama:	kusama.api.subscan.io	,
    Darwinia:	darwinia.api.subscan.io	,
Crust:	crust.api.subscan.io	,
AcalaMandala:	acala-testnet.api.subscan.io	,
Astar	:astar.api.subscan.io	,
BifrostAsgard:	bifrost.api.subscan.io	,
Centrifuge:	centrifuge.api.subscan.io	,
ChainX:	chainx.api.subscan.io	,
Clover:	clover.api.subscan.io	,
CloverTestnet:	clover-testnet.api.subscan.io	,
CrustMaxwell:	maxwell.api.subscan.io	,
DarwiniaCrab	:crab.api.subscan.io	,
DataHighway:	datahighway.api.subscan.io	,
DataHighwayHarbour:	datahighway-harbour.api.subscan.io	,
DeepBrainChain:	dbc.api.subscan.io	,
Dock	:dock.api.subscan.io	,
Edgeware	:edgeware.api.subscan.io	,
Equilibrium:	equilibrium.api.subscan.io	,
Gateway:	gateway-testnet.api.subscan.io	,
Karura:	karura.api.subscan.io	,
Kulupu:	kulupu.api.subscan.io	,
Khala:	khala.api.subscan.io	,
KILTPeregrine:	kilt-testnet.api.subscan.io	,
LaminarTC2:	laminar-testnet.api.subscan.io	,
Litentry:	litentry.api.subscan.io	,
Manta	:manta-testnet.api.subscan.io,	
Moonbase:	moonbase.api.subscan.io	,
Moonriver:	moonriver.api.subscan.io,	
Pangolin:	pangolin.api.subscan.io	,
PhalaRorschach:	phala.api.subscan.io,	
Plasm	:plasm.api.subscan.io	,
Reef	:reef.api.subscan.io	,
Robonomics:	robonomics-testnet.api.subscan.io	,
Rococo	:rococo.api.subscan.io	,
Sakura	:sakura.api.subscan.io	,
Shibuya:	shibuya.api.subscan.io	,
Shiden:	shiden.api.subscan.io	,
SORA:	sora.api.subscan.io	,
Subgame:	subgame.api.subscan.io	,
Stafi:	stafi.api.subscan.io	,
Statemine:	statemine.api.subscan.io	,
Uniarts:	uniarts.api.subscan.io	,
  Westend:	westend.api.subscan.io }