// Copyright 2019-2022 @subwallet/extension-base
// SPDX-License-Identifier: Apache-2.0

const SUBSCAN_CHAIN_MAP: Record<string, string> = {
  polkadot: 'polkadot',
  kusama: 'kusama',
  moonbeam: 'moonbeam',
  acala: 'acala',
  astar: 'astar',
  shiden: 'shiden',
  shibuya: 'shibuya',
  westend: 'westend',
  moonbase: 'moonbase',
  moonriver: 'moonriver',
  turing: 'turing',
  bifrost_testnet: 'bifrost-testnet',
  calamari: 'calamari',
  statemint: 'statemint',
  pioneer: 'pioneer',
  parallel: 'parallel',
  clover: 'clover',
  hydradx_main: 'hydradx',
  edgeware: 'edgeware',
  centrifuge: 'centrifuge-parachain',
  interlay: 'interlay',
  nodle: 'nodle',
  darwinia: 'darwinia',
  polkadex: 'polkadex',
  aleph: 'alephzero',
  dolphin: 'dolphin',
  efinity: 'efinity',
  composableFinance: 'composable',
  phala: 'phala',
  crust: 'crust',
  statemine: 'statemine',
  karura: 'karura',
  khala: 'khala',
  kilt: 'spiritnet',
  basilisk: 'basilisk',
  altair: 'altair',
  heiko: 'parallel-heiko',
  kintsugi: 'kintsugi',
  picasso: 'picasso',
  quartz: 'quartz',
  unique_network: 'unique',
  genshiro: 'genshiro',
  zeitgeist: 'zeitgeist',
  sakura: 'sakura',
  shadow: 'shadow',
  robonomics: 'robonomics',
  integritee: 'integritee',
  acala_testnet: 'acala-testnet',
  mangatax: 'mangatax',
  encointer: 'encointer',
  subspace_gemini_2a: 'subspace',
  origintrail: 'origintrail',
  bajun: 'bajun',
  snow: 'snow',
  kilt_peregrine: 'kilt-testnet',
  polymesh: 'polymesh',
  bifrost_dot: 'bifrost-p',
  vara_network: 'vara',
  bifrost: 'bifrost',
  creditcoin: 'creditcoin',
  joystream: 'joystream'
};

export const SUBSCAN_CHAIN_MAP_REVERSE = Object.fromEntries(Object.entries(SUBSCAN_CHAIN_MAP).map(([k, v]) => [v, k]));
export default SUBSCAN_CHAIN_MAP;
