// Copyright 2017-2022 @polkadot/extension-base authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/extension-base', version: '0.42.5-8' };
