// Copyright 2017-2021 @polkadot/extension-base authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/extension-base', version: '0.38.4-8' };
