// Copyright 2017-2022 @polkadot/extension-base authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/extension-base', path: 'auto', type: 'auto', version: '0.42.6-4' };
