// Copyright 2017-2021 @polkadot/extension-compat-metamask authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/extension-compat-metamask', version: '0.41.3-5' };
