// Copyright 2017-2022 @subwallet/extension-koni authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Empty template, auto-generated by @polkadot/dev

export default [];

[
    [
      [
        {
          VSBond2: [
            0
            2,000
            6
            13
          ]
        }
      ]
      {
        name: vsBOND-DOT-2000-6-13
        symbol: vsBOND-DOT-2000-6-13
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,008
            10
            17
          ]
        }
      ]
      {
        name: vsBOND-DOT-2008-10-17
        symbol: vsBOND-DOT-2008-10-17
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Token2: 6
        }
      ]
      {
        name: interBTC
        symbol: IBTC
        decimals: 8
        minimalBalance: 100
      }
    ]
    [
      [
        {
          Token2: 8
        }
      ]
      {
        name: Manta Network
        symbol: MANTA
        decimals: 18
        minimalBalance: 10,000,000,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            3,340
            14
            21
          ]
        }
      ]
      {
        name: vsBOND-DOT-3340-14-21
        symbol: vsBOND-DOT-3340-14-21
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,021
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2021-7-14
        symbol: vsBOND-DOT-2021-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Token2: 7
        }
      ]
      {
        name: Interlay
        symbol: INTR
        decimals: 10
        minimalBalance: 10,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,051
            10
            17
          ]
        }
      ]
      {
        name: vsBOND-DOT-2051-10-17
        symbol: vsBOND-DOT-2051-10-17
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            3,340
            12
            19
          ]
        }
      ]
      {
        name: vsBOND-DOT-3340-12-19
        symbol: vsBOND-DOT-3340-12-19
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,034
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2034-7-14
        symbol: vsBOND-DOT-2034-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Token2: 2
        }
      ]
      {
        name: Tether USD
        symbol: USDT
        decimals: 6
        minimalBalance: 1,000
      }
    ]
    [
      [
        {
          Token2: 5
        }
      ]
      {
        name: USD Coin
        symbol: USDC
        decimals: 6
        minimalBalance: 1,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,027
            8
            15
          ]
        }
      ]
      {
        name: vsBOND-DOT-2027-8-15
        symbol: vsBOND-DOT-2027-8-15
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Token2: 0
        }
      ]
      {
        name: Polkadot DOT
        symbol: DOT
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,003
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2003-7-14
        symbol: vsBOND-DOT-2003-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,008
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2008-7-14
        symbol: vsBOND-DOT-2008-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,036
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2036-7-14
        symbol: vsBOND-DOT-2036-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          BLP: 0
        }
      ]
      {
        name: Bifrost Stable Pool Token 0
        symbol: BLP0
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            3,338
            13
            20
          ]
        }
      ]
      {
        name: vsBOND-DOT-3338-13-20
        symbol: vsBOND-DOT-3338-13-20
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,039
            9
            16
          ]
        }
      ]
      {
        name: vsBOND-DOT-2039-9-16
        symbol: vsBOND-DOT-2039-9-16
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Token2: 1
        }
      ]
      {
        name: Moonbeam Native Token
        symbol: GLMR
        decimals: 18
        minimalBalance: 1,000,000,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,025
            15
            22
          ]
        }
      ]
      {
        name: vsBOND-DOT-2025-15-22
        symbol: vsBOND-DOT-2025-15-22
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,013
            6
            13
          ]
        }
      ]
      {
        name: vsBOND-DOT-2013-6-13
        symbol: vsBOND-DOT-2013-6-13
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,004
            6
            13
          ]
        }
      ]
      {
        name: vsBOND-DOT-2004-6-13
        symbol: vsBOND-DOT-2004-6-13
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VToken2: 1
        }
      ]
      {
        name: Voucher GLMR
        symbol: vGLMR
        decimals: 18
        minimalBalance: 1,000,000,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,015
            6
            13
          ]
        }
      ]
      {
        name: vsBOND-DOT-2015-6-13
        symbol: vsBOND-DOT-2015-6-13
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            3,340
            13
            20
          ]
        }
      ]
      {
        name: vsBOND-DOT-3340-13-20
        symbol: vsBOND-DOT-3340-13-20
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,035
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2035-7-14
        symbol: vsBOND-DOT-2035-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,027
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2027-7-14
        symbol: vsBOND-DOT-2027-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          BLP: 1
        }
      ]
      {
        name: Bifrost Stable Pool Token 1
        symbol: BLP1
        decimals: 18
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VToken2: 4
        }
      ]
      {
        name: Voucher FIL
        symbol: vFIL
        decimals: 18
        minimalBalance: 1,000,000,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,006
            6
            13
          ]
        }
      ]
      {
        name: vsBOND-DOT-2006-6-13
        symbol: vsBOND-DOT-2006-6-13
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Token2: 9
        }
      ]
      {
        name: bncs-20 inscription token BNCS
        symbol: BNCS
        decimals: 12
        minimalBalance: 10,000,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,018
            6
            13
          ]
        }
      ]
      {
        name: vsBOND-DOT-2018-6-13
        symbol: vsBOND-DOT-2018-6-13
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,032
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2032-7-14
        symbol: vsBOND-DOT-2032-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Token2: 10
        }
      ]
      {
        name: PINK
        symbol: PINK
        decimals: 10
        minimalBalance: 100,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            3,354
            15
            22
          ]
        }
      ]
      {
        name: vsBOND-DOT-3354-15-22
        symbol: vsBOND-DOT-3354-15-22
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,013
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2013-7-14
        symbol: vsBOND-DOT-2013-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Token2: 4
        }
      ]
      {
        name: Filecoin Network Token
        symbol: FIL
        decimals: 18
        minimalBalance: 1,000,000,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,043
            8
            15
          ]
        }
      ]
      {
        name: vsBOND-DOT-2043-8-15
        symbol: vsBOND-DOT-2043-8-15
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,037
            8
            15
          ]
        }
      ]
      {
        name: vsBOND-DOT-2037-8-15
        symbol: vsBOND-DOT-2037-8-15
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            3,345
            14
            21
          ]
        }
      ]
      {
        name: vsBOND-DOT-3345-14-21
        symbol: vsBOND-DOT-3345-14-21
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            3,341
            14
            21
          ]
        }
      ]
      {
        name: vsBOND-DOT-3341-14-21
        symbol: vsBOND-DOT-3341-14-21
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VToken2: 3
        }
      ]
      {
        name: Voucher ASTR
        symbol: vASTR
        decimals: 18
        minimalBalance: 10,000,000,000,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,013
            8
            15
          ]
        }
      ]
      {
        name: vsBOND-DOT-2013-8-15
        symbol: vsBOND-DOT-2013-8-15
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,021
            6
            13
          ]
        }
      ]
      {
        name: vsBOND-DOT-2021-6-13
        symbol: vsBOND-DOT-2021-6-13
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,019
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2019-7-14
        symbol: vsBOND-DOT-2019-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,090
            10
            17
          ]
        }
      ]
      {
        name: vsBOND-DOT-2090-10-17
        symbol: vsBOND-DOT-2090-10-17
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            3,338
            12
            19
          ]
        }
      ]
      {
        name: vsBOND-DOT-3338-12-19
        symbol: vsBOND-DOT-3338-12-19
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Native: BNC
        }
      ]
      {
        name: Bifrost Native Token
        symbol: BNC
        decimals: 12
        minimalBalance: 10,000,000,000
      }
    ]
    [
      [
        {
          VToken2: 0
        }
      ]
      {
        name: Voucher DOT
        symbol: vDOT
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            3,356
            15
            22
          ]
        }
      ]
      {
        name: vsBOND-DOT-3356-15-22
        symbol: vsBOND-DOT-3356-15-22
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,025
            14
            21
          ]
        }
      ]
      {
        name: vsBOND-DOT-2025-14-21
        symbol: vsBOND-DOT-2025-14-21
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,030
            8
            15
          ]
        }
      ]
      {
        name: vsBOND-DOT-2030-8-15
        symbol: vsBOND-DOT-2030-8-15
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,040
            8
            15
          ]
        }
      ]
      {
        name: vsBOND-DOT-2040-8-15
        symbol: vsBOND-DOT-2040-8-15
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          Token2: 3
        }
      ]
      {
        name: Astar
        symbol: ASTR
        decimals: 18
        minimalBalance: 10,000,000,000,000,000
      }
    ]
    [
      [
        {
          VSToken2: 0
        }
      ]
      {
        name: Voucher Slot DOT
        symbol: vsDOT
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,026
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2026-7-14
        symbol: vsBOND-DOT-2026-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          BLP: 4
        }
      ]
      {
        name: Bifrost Stable Pool Token 4
        symbol: BLP4
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          VSBond2: [
            0
            2,031
            7
            14
          ]
        }
      ]
      {
        name: vsBOND-DOT-2031-7-14
        symbol: vsBOND-DOT-2031-7-14
        decimals: 10
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          BLP: 2
        }
      ]
      {
        name: Bifrost Stable Pool Token 2
        symbol: BLP2
        decimals: 18
        minimalBalance: 1,000,000
      }
    ]
    [
      [
        {
          BLP: 3
        }
      ]
      {
        name: Bifrost Stable Pool Token 3
        symbol: BLP3
        decimals: 18
        minimalBalance: 1,000,000
      }
    ]
]