// Copyright 2017-2022 @subwallet/extension-chains authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@subwallet/extension-chains', path: 'auto', type: 'auto', version: '0.3.6-0' };
