// Copyright 2017-2021 @polkadot/extension-chains authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/extension-chains', version: '0.41.3-5' };
