"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.packageInfo = void 0;
// Copyright 2017-2022 @polkadot/extension-compat-metamask authors & contributors
// SPDX-License-Identifier: Apache-2.0
// Do not edit, auto-generated by @polkadot/dev
const packageInfo = {
  name: '@polkadot/extension-compat-metamask',
  path: typeof __dirname === 'string' ? __dirname : 'auto',
  type: 'cjs',
  version: '0.3.5-0'
};
exports.packageInfo = packageInfo;