// Copyright 2017-2024 @polkadot/extension-dapp authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/extension-dapp', path: 'auto', type: 'auto', version: '0.51.2-2-x' };
