"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

var _util = require("@polkadot/util");

var _detectOther = _interopRequireDefault(require("./detectOther"));

var _packageInfo = require("./packageInfo");

// Copyright 2017-2022 @polkadot/extension-inject authors & contributors
// SPDX-License-Identifier: Apache-2.0
// Do not edit, auto-generated by @polkadot/dev
(0, _util.detectPackage)(_packageInfo.packageInfo, null, _detectOther.default);