// Copyright 2017-2022 @subwallet/webapp authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@subwallet/webapp', path: 'auto', type: 'auto', version: '1.0.12-0' };
