// Copyright 2017-2024 @polkadot/extension-rpc authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/extension-rpc', path: 'auto', type: 'auto', version: '0.48.3-2-x' };
